build-airport:
  stage: build
  script:
    - cd airports
    - docker build .

build-gateway:
  stage: build
  script:
    - cd gateway
    - docker build .

build-trips:
  stage: build
  script:
    - cd trips
    - docker build .