preparation:
  stage: prepare
  script:
    - echo "BUILD_ID=$(date +%Y%m%d%H%M)" > context.env
  artifacts: 
    paths: 
      - context.env

build-airport:
  stage: build
  script:
    - . context.env
    - cd airports
    - docker build . -t airport:${BUILD_ID}
  dependencies:
    - preparation

build-gateway:
  stage: build
  script:
    - cd gateway
    - docker build .

build-trips:
  stage: build
  script:
    - cd trips
    - docker build .

test-airport:
  stage: testing
  script:
    - docker run --rm     